version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: masterglobal_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - erp-net

  backend:
    build: ./backend
    container_name: erp-backend
    ports:
      - "8080:8080"
      - "8888:8888"   # ðŸ‘ˆ TEMP for Google OAuth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/masterglobal_erp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./backend/tokens:/app/tokens   # âœ… MOUNT TOKENS
    depends_on:
      - db
    networks:
      - erp-net

  frontend:
    build: ./frontend
    container_name: erp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - erp-net

volumes:
  db_data:

networks:
  erp-net:
    driver: bridge
